#pragma once
namespace shtools {
extern "C"
{
  void PlmBar(double* p,
              const int p_d0,
              const int lmax,
              const double z,
              const int* csphase,
              const int* cnorm,
              int* exitstatus);
  void PlmBar_d1(double* p,
                 const int p_d0,
                 double* dp1,
                 const int dp1_d0,
                 const int lmax,
                 const double z,
                 const int* csphase,
                 const int* cnorm,
                 int* exitstatus);
  void PlBar(double* p,
             const int p_d0,
             const int lmax,
             const double z,
             int* exitstatus);
  void PlBar_d1(double* p,
                const int p_d0,
                double* dp1,
                const int dp1_d0,
                const int lmax,
                const double z,
                int* exitstatus);
  void PlmON(double* p,
             const int p_d0,
             const int lmax,
             const double z,
             const int* csphase,
             const int* cnorm,
             int* exitstatus);
  void PlmON_d1(double* p,
                const int p_d0,
                double* dp1,
                const int dp1_d0,
                const int lmax,
                const double z,
                const int* csphase,
                const int* cnorm,
                int* exitstatus);
  void PlON(double* p,
            const int p_d0,
            const int lmax,
            const double z,
            int* exitstatus);
  void PlON_d1(double* p,
               const int p_d0,
               double* dp1,
               const int dp1_d0,
               const int lmax,
               const double z,
               int* exitstatus);
  void PlmSchmidt(double* p,
                  const int p_d0,
                  const int lmax,
                  const double z,
                  const int* csphase,
                  const int* cnorm,
                  int* exitstatus);
  void PlmSchmidt_d1(double* p,
                     const int p_d0,
                     double* dp1,
                     const int dp1_d0,
                     const int lmax,
                     const double z,
                     const int* csphase,
                     const int* cnorm,
                     int* exitstatus);
  void PlSchmidt(double* p,
                 const int p_d0,
                 const int lmax,
                 const double z,
                 int* exitstatus);
  void PlSchmidt_d1(double* p,
                    const int p_d0,
                    double* dp1,
                    const int dp1_d0,
                    const int lmax,
                    const double z,
                    int* exitstatus);
  void PLegendreA(double* p,
                  const int p_d0,
                  const int lmax,
                  const double z,
                  const int* csphase,
                  int* exitstatus);
  void PLegendreA_d1(double* p,
                     const int p_d0,
                     double* dp1,
                     const int dp1_d0,
                     const int lmax,
                     const double z,
                     const int* csphase,
                     int* exitstatus);
  void PLegendre(double* p,
                 const int p_d0,
                 const int lmax,
                 const double z,
                 int* exitstatus);
  void PLegendre_d1(double* p,
                    const int p_d0,
                    double* dp1,
                    const int dp1_d0,
                    const int lmax,
                    const double z,
                    int* exitstatus);
  int PlmIndex(const int l, const int m);
  void SHExpandDH(const double* grid,
                  const int grid_d0,
                  const int grid_d1,
                  const int n,
                  double* cilm,
                  const int cilm_d,
                  int* lmax,
                  const int* norm,
                  const int* sampling,
                  const int* csphase,
                  const int* lmax_calc,
                  int* exitstatus);
  void MakeGridDH(double* griddh,
                  const int griddh_d0,
                  const int griddh_d1,
                  int* n,
                  const double* cilm,
                  const int cilm_d,
                  const int lmax,
                  const int* norm,
                  const int* sampling,
                  const int* csphase,
                  const int* lmax_calc,
                  const int* extend,
                  int* exitstatus);
  void SHExpandDHC(const double _Complex* grid,
                   const int grid_d0,
                   const int grid_d1,
                   const int n,
                   double _Complex* cilm,
                   const int cilm_d,
                   int* lmax,
                   const int* norm,
                   const int* sampling,
                   const int* csphase,
                   const int* lmax_calc,
                   int* exitstatus);
  void MakeGridDHC(double _Complex* griddh,
                   const int griddh_d0,
                   const int griddh_d1,
                   int* n,
                   const double _Complex* cilm,
                   const int cilm_d,
                   const int lmax,
                   const int* norm,
                   const int* sampling,
                   const int* csphase,
                   const int* lmax_calc,
                   const int* extend,
                   int* exitstatus);
  void SHGLQ(const int lmax,
             double* zero,
             const int zero_d0,
             double* w,
             const int w_d0,
             double* plx,
             const int plx_d0,
             const int plx_d1,
             const int* norm,
             const int* csphase,
             const int* cnorm,
             int* exitstatus);
  void SHExpandGLQ(double* cilm,
                   const int cilm_d,
                   const int lmax,
                   const double* gridglq,
                   const int gridglq_d0,
                   const int gridglq_d1,
                   const double* w,
                   const int w_d0,
                   const double* plx,
                   const int plx_d0,
                   const int plx_d1,
                   const double* zero,
                   const int zero_d0,
                   const int* norm,
                   const int* csphase,
                   const int* lmax_calc,
                   int* exitstatus);
  void MakeGridGLQ(double* gridglq,
                   const int gridglq_d0,
                   const int gridglq_d1,
                   const double* cilm,
                   const int cilm_d,
                   const int lmax,
                   const double* plx,
                   const int plx_d0,
                   const int plx_d1,
                   const double* zero,
                   const int zero_d0,
                   const int* norm,
                   const int* csphase,
                   const int* lmax_calc,
                   const int* extend,
                   int* exitstatus);
  void SHExpandGLQC(double _Complex* cilm,
                    const int cilm_d,
                    const int lmax,
                    const double _Complex* gridglq,
                    const int gridglq_d0,
                    const int gridglq_d1,
                    const double* w,
                    const int w_d0,
                    const double* plx,
                    const int plx_d0,
                    const int plx_d1,
                    const double* zero,
                    const int zero_d0,
                    const int* norm,
                    const int* csphase,
                    const int* lmax_calc,
                    int* exitstatus);
  void MakeGridGLQC(double _Complex* gridglq,
                    const int gridglq_d0,
                    const int gridglq_d1,
                    const double _Complex* cilm,
                    const int cilm_d,
                    const int lmax,
                    const double* plx,
                    const int plx_d0,
                    const int plx_d1,
                    const double* zero,
                    const int zero_d0,
                    const int* norm,
                    const int* csphase,
                    const int* lmax_calc,
                    const int* extend,
                    int* exitstatus);
  void GLQGridCoord(double* latglq,
                    const int latglq_d0,
                    double* longlq,
                    const int longlq_d0,
                    const int lmax,
                    int* nlat,
                    int* nlong,
                    const int* extend,
                    int* exitstatus);
  void SHExpandLSQ(double* cilm,
                   const int cilm_d,
                   const double* d,
                   const int d_d0,
                   const double* lat,
                   const int lat_d0,
                   const double* lon,
                   const int lon_d0,
                   const int nmax,
                   const int lmax,
                   const int* norm,
                   double* chi2,
                   const int* csphase,
                   const double* weights,
                   const int weights_d0,
                   int* exitstatus);
  void MakeGrid2d(double* grid,
                  const int grid_d0,
                  const int grid_d1,
                  const double* cilm,
                  const int cilm_d,
                  const int lmax,
                  const double interval,
                  int* nlat,
                  int* nlong,
                  const int* norm,
                  const int* csphase,
                  const double* f,
                  const double* a,
                  const double* north,
                  const double* south,
                  const double* east,
                  const double* west,
                  const int* dealloc,
                  int* exitstatus);
  double MakeGridPoint(const double* cilm,
                       const int cilm_d,
                       const int lmax,
                       const double lat,
                       const double lon,
                       const int* norm,
                       const int* csphase,
                       const int* dealloc);
  double _Complex MakeGridPointC(const double _Complex* cilm,
                                 const int cilm_d,
                                 const int lmax,
                                 const double lat,
                                 const double lon,
                                 const int* norm,
                                 const int* csphase,
                                 const int* dealloc);
  void SHMultiply(double* shout,
                  const int shout_d0,
                  const int shout_d1,
                  const int shout_d2,
                  const double* sh1,
                  const int sh1_d0,
                  const int sh1_d1,
                  const int sh1_d2,
                  const int lmax1,
                  const double* sh2,
                  const int sh2_d0,
                  const int sh2_d1,
                  const int sh2_d2,
                  const int lmax2,
                  const int* precomp,
                  const int* norm,
                  const int* csphase,
                  int* exitstatus);
  void SHRead(const char* filename,
              const int filename_d1,
              double* cilm,
              const int cilm_d,
              int* lmax,
              const int* skip,
              double* header,
              const int header_d0,
              double* error,
              const int error_d0,
              const int error_d1,
              const int error_d2,
              int* exitstatus);
  void SHRead2(const char* filename,
               const int filename_d1,
               double* cilm,
               const int cilm_d,
               int* lmax,
               double* gm,
               double* r0_pot,
               double* error,
               const int error_d0,
               const int error_d1,
               const int error_d2,
               double* dot,
               const int dot_d0,
               const int dot_d1,
               const int dot_d2,
               double* doystart,
               double* doyend,
               double* epoch,
               int* exitstatus);
  void SHReadJPL(const char* filename,
                 const int filename_d1,
                 double* cilm,
                 const int cilm_d,
                 const int lmax,
                 double* error,
                 const int error_d0,
                 const int error_d1,
                 const int error_d2,
                 double* gm,
                 const char* formatstring,
                 int* exitstatus);
  void SHCilmToVector(const double* cilm,
                      double* vector,
                      const int lmax,
                      int* exitstatus);
  void SHVectorToCilm(const double* vector,
                      const int vector_d0,
                      double* cilm,
                      const int cilm_d,
                      const int lmax,
                      int* exitstatus);
  void SHCilmToCindex(const double* cilm,
                      const int cilm_d,
                      double* cindex,
                      const int cindex_d0,
                      const int cindex_d1,
                      const int* degmax,
                      int* exitstatus);
  void SHCindexToCilm(const double* cindex,
                      const int cindex_d0,
                      const int cindex_d1,
                      double* cilm,
                      const int cilm_d,
                      const int* degmax,
                      int* exitstatus);
  void SHrtoc(const double* rcilm,
              const int rcilm_d0,
              const int rcilm_d1,
              const int rcilm_d2,
              double* ccilm,
              const int ccilm_d0,
              const int ccilm_d1,
              const int ccilm_d2,
              const int* degmax,
              const int* convention,
              const int* switchcs,
              int* exitstatus);
  void SHctor(const double* ccilm,
              const int ccilm_d0,
              const int ccilm_d1,
              const int ccilm_d2,
              double* rcilm,
              const int rcilm_d0,
              const int rcilm_d1,
              const int rcilm_d2,
              const int* degmax,
              const int* convention,
              const int* switchcs,
              int* exitstatus);
  void djpi2(double* dj,
             const int dj_d0,
             const int dj_d1,
             const int dj_d2,
             const int lmax,
             int* exitstatus);
  void SHRotateCoef(const double* x,
                    const double* cof,
                    const int cof_d0,
                    const int cof_d1,
                    double* rcof,
                    const int rcof_d0,
                    const int rcof_d1,
                    const double* dj,
                    const int dj_d0,
                    const int dj_d1,
                    const int dj_d2,
                    const int lmax,
                    int* exitstatus);
  void SHRotateRealCoef(double* cilmrot,
                        const int cilmrot_d0,
                        const int cilmrot_d1,
                        const int cilmrot_d2,
                        const double* cilm,
                        const int cilm_d,
                        const int lmax,
                        const double* x,
                        const int x_d0,
                        const double* dj,
                        const int dj_d0,
                        const int dj_d1,
                        const int dj_d2,
                        int* exitstatus);
  double SHPowerL(const double* c,
                  const int c_d0,
                  const int c_d1,
                  const int c_d2,
                  const int l);
  double SHPowerDensityL(const double* c,
                         const int c_d0,
                         const int c_d1,
                         const int c_d2,
                         const int l);
  double SHCrossPowerL(const double* c1,
                       const int c1_d0,
                       const int c1_d1,
                       const int c1_d2,
                       const double* c2,
                       const int c2_d0,
                       const int c2_d1,
                       const int c2_d2,
                       const int l);
  double SHCrossPowerDensityL(const double* c1,
                              const int c1_d0,
                              const int c1_d1,
                              const int c1_d2,
                              const double* c2,
                              const int c2_d0,
                              const int c2_d1,
                              const int c2_d2,
                              const int l);
  void SHPowerSpectrum(const double* c,
                       const int c_d0,
                       const int c_d1,
                       const int c_d2,
                       const int lmax,
                       double* spectra,
                       const int spectra_d0,
                       int* exitstatus);
  void SHPowerSpectrumDensity(const double* c,
                              const int c_d0,
                              const int c_d1,
                              const int c_d2,
                              const int lmax,
                              double* spectra,
                              const int spectra_d0,
                              int* exitstatus);
  void SHCrossPowerSpectrum(const double* c1,
                            const int c1_d0,
                            const int c1_d1,
                            const int c1_d2,
                            const double* c2,
                            const int c2_d0,
                            const int c2_d1,
                            const int c2_d2,
                            const int lmax,
                            double* cspectra,
                            const int cspectra_d0,
                            int* exitstatus);
  void SHCrossPowerSpectrumDensity(const double* c1,
                                   const int c1_d0,
                                   const int c1_d1,
                                   const int c1_d2,
                                   const double* c2,
                                   const int c2_d0,
                                   const int c2_d1,
                                   const int c2_d2,
                                   const int lmax,
                                   double* cspectra,
                                   const int cspectra_d0,
                                   int* exitstatus);
  void SHAdmitCorr(const double* G,
                   const int G_d0,
                   const int G_d1,
                   const int G_d2,
                   const double* T,
                   const int T_d0,
                   const int T_d1,
                   const int T_d2,
                   const int lmax,
                   double* admit,
                   const int admit_d0,
                   double* corr,
                   const int corr_d0,
                   double* admit_error,
                   const int admit_error_d0,
                   int* exitstatus);
  double SHConfidence(const int l_conf, const double r);
  double SHPowerLC(const double _Complex* c,
                   const int c_d0,
                   const int c_d1,
                   const int c_d2,
                   const int l);
  double SHPowerDensityLC(const double _Complex* c,
                          const int c_d0,
                          const int c_d1,
                          const int c_d2,
                          const int l);
  double _Complex SHCrossPowerLC(const double _Complex* c1,
                                 const int c1_d0,
                                 const int c1_d1,
                                 const int c1_d2,
                                 const double _Complex* c2,
                                 const int c2_d0,
                                 const int c2_d1,
                                 const int c2_d2,
                                 const int l);
  double _Complex SHCrossPowerDensityLC(const double _Complex* c1,
                                        const int c1_d0,
                                        const int c1_d1,
                                        const int c1_d2,
                                        const double _Complex* c2,
                                        const int c2_d0,
                                        const int c2_d1,
                                        const int c2_d2,
                                        const int l);
  void SHPowerSpectrumC(const double _Complex* c,
                        const int c_d0,
                        const int c_d1,
                        const int c_d2,
                        const int lmax,
                        double* spectra,
                        const int spectra_d0,
                        int* exitstatus);
  void SHPowerSpectrumDensityC(const double _Complex* c,
                               const int c_d0,
                               const int c_d1,
                               const int c_d2,
                               const int lmax,
                               double* spectra,
                               const int spectra_d0,
                               int* exitstatus);
  void SHCrossPowerSpectrumC(const double _Complex* c1,
                             const int c1_d0,
                             const int c1_d1,
                             const int c1_d2,
                             const double _Complex* c2,
                             const int c2_d0,
                             const int c2_d1,
                             const int c2_d2,
                             const int lmax,
                             double _Complex* cspectra,
                             const int cspectra_d0,
                             int* exitstatus);
  void SHCrossPowerSpectrumDensityC(const double _Complex* c1,
                                    const int c1_d0,
                                    const int c1_d1,
                                    const int c1_d2,
                                    const double _Complex* c2,
                                    const int c2_d0,
                                    const int c2_d1,
                                    const int c2_d2,
                                    const int lmax,
                                    double _Complex* cspectra,
                                    const int cspectra_d0,
                                    int* exitstatus);
  void SHMultiTaperSE(double* mtse,
                      const int mtse_d0,
                      double* sd,
                      const int sd_d0,
                      const double* sh,
                      const int sh_d0,
                      const int sh_d1,
                      const int sh_d2,
                      const int lmax,
                      const double* tapers,
                      const int tapers_d0,
                      const int tapers_d1,
                      const int* taper_order,
                      const int taper_order_d0,
                      const int lmaxt,
                      const int k,
                      const double* alpha,
                      const int alpha_d0,
                      const double* lat,
                      const double* lon,
                      const double* taper_wt,
                      const int taper_wt_d0,
                      const int* norm,
                      const int* csphase,
                      int* exitstatus);
  void SHMultiTaperCSE(double* mtse,
                       const int mtse_d0,
                       double* sd,
                       const int sd_d0,
                       const double* sh1,
                       const int sh1_d0,
                       const int sh1_d1,
                       const int sh1_d2,
                       const int lmax1,
                       const double* sh2,
                       const int sh2_d0,
                       const int sh2_d1,
                       const int sh2_d2,
                       const int lmax2,
                       const double* tapers,
                       const int tapers_d0,
                       const int tapers_d1,
                       const int* taper_order,
                       const int taper_order_d0,
                       const int lmaxt,
                       const int k,
                       const double* alpha,
                       const int alpha_d0,
                       const double* lat,
                       const double* lon,
                       const double* taper_wt,
                       const int taper_wt_d0,
                       const int* norm,
                       const int* csphase,
                       int* exitstatus);
  void SHLocalizedAdmitCorr(const double* tapers,
                            const int tapers_d0,
                            const int tapers_d1,
                            const int* taper_order,
                            const int taper_order_d0,
                            const int lwin,
                            const double lat,
                            const double lon,
                            const double* g,
                            const int g_d0,
                            const int g_d1,
                            const int g_d2,
                            const double* t,
                            const int t_d0,
                            const int t_d1,
                            const int t_d2,
                            const int lmax,
                            double* admit,
                            const int admit_d0,
                            double* corr,
                            const int corr_d0,
                            const int k,
                            double* admit_error,
                            const int admit_error_d0,
                            double* corr_error,
                            const int corr_error_d0,
                            const double* taper_wt,
                            const int taper_wt_d0,
                            const int* mtdef,
                            const int* k1linsig,
                            int* exitstatus);
  void SHReturnTapers(const double theta0,
                      const int lmax,
                      double* tapers,
                      const int tapers_d0,
                      const int tapers_d1,
                      double* eigenvalues,
                      const int eigenvalues_d0,
                      int* taper_order,
                      const int taper_order_d0,
                      const int* degrees,
                      const int degrees_d0,
                      int* exitstatus);
  void SHReturnTapersM(const double theta0,
                       const int lmax,
                       const int m,
                       double* tapers,
                       const int tapers_d0,
                       const int tapers_d1,
                       double* eigenvalues,
                       const int eigenvalues_d0,
                       double* shannon,
                       const int* degrees,
                       const int degrees_d0,
                       int* ntapers,
                       int* exitstatus);
  void ComputeDm(double* dllm,
                 const int dllm_d0,
                 const int dllm_d1,
                 const int lmax,
                 const int m,
                 const double theta0,
                 const int* degrees,
                 const int degrees_d0,
                 int* exitstatus);
  void ComputeDG82(double* dG82,
                   const int dG82_d0,
                   const int dG82_d1,
                   const int lmax,
                   const int m,
                   const double theta0,
                   int* exitstatus);
  int SHFindLWin(const double theta0,
                 const int m,
                 const double alpha,
                 const int* taper_number);
  void SHBiasK(const double* tapers,
               const int tapers_d0,
               const int tapers_d1,
               const int lwin,
               const int k,
               const double* incspectra,
               const int incspectra_d0,
               const int ldata,
               double* outcspectra,
               const int outcspectra_d0,
               const double* taper_wt,
               const int taper_wt_d0,
               const int* save_cg,
               int* exitstatus);
  void SHMTCouplingMatrix(double* Mmt,
                          const int Mmt_d0,
                          const int Mmt_d1,
                          const int lmax,
                          const double* tapers_power,
                          const int tapers_power_d0,
                          const int tapers_power_d1,
                          const int lwin,
                          const int k,
                          const double* taper_wt,
                          const int taper_wt_d0,
                          int* exitstatus);
  void SHBiasAdmitCorr(const double* sgt,
                       const int sgt_d0,
                       const double* sgg,
                       const int sgg_d0,
                       const double* stt,
                       const int stt_d0,
                       const int lmax,
                       const double* tapers,
                       const int tapers_d0,
                       const int tapers_d1,
                       const int lwin,
                       const int k,
                       double* admit,
                       const int admit_d0,
                       double* corr,
                       const int corr_d0,
                       const int* mtdef,
                       const double* taper_wt,
                       const int taper_wt_d0,
                       int* exitstatus);
  void SHMTDebias(double* mtdebias,
                  const int mtdebias_d0,
                  const int mtdebias_d1,
                  const double* mtspectra,
                  const int mtspectra_d0,
                  const int mtspectra_d1,
                  const int lmax,
                  const double* tapers,
                  const int tapers_d0,
                  const int tapers_d1,
                  const int lwin,
                  const int k,
                  const int nl,
                  double* lmid,
                  const int lmid_d0,
                  int* n,
                  const double* taper_wt,
                  const int taper_wt_d0,
                  int* exitstatus);
  void SHMTVarOpt(const int l,
                  const double* tapers,
                  const int tapers_d0,
                  const int tapers_d1,
                  const int* taper_order,
                  const int taper_order_d0,
                  const int lwin,
                  const int kmax,
                  const double* Sff,
                  const int Sff_d0,
                  double* var_opt,
                  const int var_opt_d0,
                  double* var_unit,
                  const int var_unit_d0,
                  double* weight_opt,
                  const int weight_opt_d0,
                  const int weight_opt_d1,
                  double* unweighted_covar,
                  const int unweighted_covar_d0,
                  const int unweighted_covar_d1,
                  const int* nocross,
                  int* exitstatus);
  void SHMTVar(const int l,
               const double* tapers,
               const int tapers_d0,
               const int tapers_d1,
               const int* taper_order,
               const int taper_order_d0,
               const int lwin,
               const int kmax,
               const double* Sff,
               const int Sff_d0,
               double* variance,
               const double* taper_wt,
               const int taper_wt_d0,
               double* unweighted_covar,
               const int unweighted_covar_d0,
               const int unweighted_covar_d1,
               const int* nocross,
               int* exitstatus);
  double _Complex SHSjkPG(const double* incspectra,
                          const int incspectra_d0,
                          const int l,
                          const int m,
                          const int mprime,
                          const double* hj_real,
                          const int hj_real_d0,
                          const double* hk_real,
                          const int hk_real_d0,
                          const int mj,
                          const int mk,
                          const int lwin,
                          const int hkcc);
  void SHReturnTapersMap(double* tapers,
                         const int tapers_d0,
                         const int tapers_d1,
                         double* eigenvalues,
                         const int eigenvalues_d0,
                         const int* dh_mask,
                         const int dh_mask_d0,
                         const int dh_mask_d1,
                         const int n_dh,
                         const int lmax,
                         const int sampling,
                         const int* ntapers,
                         const int* degrees,
                         const int degrees_d0,
                         int* exitstatus);
  void SHBiasKMask(const double* tapers,
                   const int tapers_d0,
                   const int tapers_d1,
                   const int lwin,
                   const int k,
                   const double* incspectra,
                   const int incspectra_d0,
                   const int ldata,
                   double* outcspectra,
                   const int outcspectra_d0,
                   const double* taper_wt,
                   const int taper_wt_d0,
                   const int* save_cg,
                   int* exitstatus);
  void SHMultiTaperMaskSE(double* mtse,
                          const int mtse_d0,
                          double* sd,
                          const int sd_d0,
                          const double* sh,
                          const int sh_d0,
                          const int sh_d1,
                          const int sh_d2,
                          const int lmax,
                          const double* tapers,
                          const int tapers_d0,
                          const int tapers_d1,
                          const int lmaxt,
                          const int k,
                          const double* taper_wt,
                          const int taper_wt_d0,
                          const int* norm,
                          const int* csphase,
                          int* exitstatus);
  void SHMultiTaperMaskCSE(double* mtse,
                           const int mtse_d0,
                           double* sd,
                           const int sd_d0,
                           const double* sh1,
                           const int sh1_d0,
                           const int sh1_d1,
                           const int sh1_d2,
                           const int lmax1,
                           const double* sh2,
                           const int sh2_d0,
                           const int sh2_d1,
                           const int sh2_d2,
                           const int lmax2,
                           const double* tapers,
                           const int tapers_d0,
                           const int tapers_d1,
                           const int lmaxt,
                           const int k,
                           const double* taper_wt,
                           const int taper_wt_d0,
                           const int* norm,
                           const int* csphase,
                           int* exitstatus);
  void ComputeDMap(double* Dij,
                   const int Dij_d0,
                   const int Dij_d1,
                   const int* dh_mask,
                   const int dh_mask_d0,
                   const int dh_mask_d1,
                   const int n_dh,
                   const int lmax,
                   const int* sampling,
                   const int* degrees,
                   const int degrees_d0,
                   int* exitstatus);
  void Curve2Mask(int* dhgrid,
                  const int dhgrid_d0,
                  const int dhgrid_d1,
                  const int n,
                  const int sampling,
                  const double* profile,
                  const int profile_d0,
                  const int profile_d1,
                  const int nprofile,
                  int* NP,
                  const int* extend,
                  int* exitstatus);
  void SHBias(const double* Shh,
              const int Shh_d0,
              const int lwin,
              const double* incspectra,
              const int incspectra_d0,
              const int ldata,
              double* outcspectra,
              const int outcspectra_d0,
              const int* save_cg,
              int* exitstatus);
  void SphericalCapCoef(double* coef,
                        const int coef_d0,
                        const double theta,
                        const int* lmax,
                        int* exitstatus);
  void MakeGravGridDH(const double* cilm,
                      const int cilm_d,
                      const int lmax,
                      const double gm,
                      const double r0,
                      const double a,
                      const double f,
                      double* rad,
                      const int rad_d0,
                      const int rad_d1,
                      double* theta,
                      const int theta_d0,
                      const int theta_d1,
                      double* phi,
                      const int phi_d0,
                      const int phi_d1,
                      double* total,
                      const int total_d0,
                      const int total_d1,
                      int* n,
                      const int* sampling,
                      const int* lmax_calc,
                      const double* omega,
                      const int* normal_gravity,
                      double* pot,
                      const int pot_d0,
                      const int pot_d1,
                      const int* extend,
                      int* exitstatus);
  void MakeGravGradGridDH(const double* cilm,
                          const int cilm_d,
                          const int lmax,
                          const double gm,
                          const double r0,
                          const double a,
                          const double f,
                          double* vxx,
                          const int vxx_d0,
                          const int vxx_d1,
                          double* vyy,
                          const int vyy_d0,
                          const int vyy_d1,
                          double* vzz,
                          const int vzz_d0,
                          const int vzz_d1,
                          double* vxy,
                          const int vxy_d0,
                          const int vxy_d1,
                          double* vxz,
                          const int vxz_d0,
                          const int vxz_d1,
                          double* vyz,
                          const int vyz_d0,
                          const int vyz_d1,
                          int* n,
                          const int* sampling,
                          const int* lmax_calc,
                          const int* extend,
                          int* exitstatus);
  void MakeMagGradGridDH(const double* cilm,
                         const int cilm_d,
                         const int lmax,
                         const double r0,
                         const double a,
                         const double f,
                         double* vxx,
                         const int vxx_d0,
                         const int vxx_d1,
                         double* vyy,
                         const int vyy_d0,
                         const int vyy_d1,
                         double* vzz,
                         const int vzz_d0,
                         const int vzz_d1,
                         double* vxy,
                         const int vxy_d0,
                         const int vxy_d1,
                         double* vxz,
                         const int vxz_d0,
                         const int vxz_d1,
                         double* vyz,
                         const int vyz_d0,
                         const int vyz_d1,
                         int* n,
                         const int* sampling,
                         const int* lmax_calc,
                         const int* extend,
                         int* exitstatus);
  void MakeGeoidGrid(double* geoid,
                     const int geoid_d0,
                     const int geoid_d1,
                     const double* cilm,
                     const int cilm_d,
                     const int lmax,
                     const double r0pot,
                     const double GM,
                     const double PotRef,
                     const double omega,
                     const double r,
                     const int gridtype,
                     const int order,
                     int* nlat,
                     int* nlong,
                     const double* interval,
                     const int* lmax_calc,
                     const double* a,
                     const double* f,
                     const int* extend,
                     int* exitstatus);
  void CilmPlus(double* cilm,
                const int cilm_d,
                const double* gridin,
                const int gridin_d0,
                const int gridin_d1,
                const int lmax,
                const int nmax,
                const double mass,
                double* d,
                const double rho,
                const int gridtype,
                const double* w,
                const int w_d0,
                const double* zero,
                const int zero_d0,
                const double* plx,
                const int plx_d0,
                const int plx_d1,
                const int* n,
                const double* dref,
                int* exitstatus);
  void CilmMinus(double* cilm,
                 const int cilm_d,
                 const double* gridin,
                 const int gridin_d0,
                 const int gridin_d1,
                 const int lmax,
                 const int nmax,
                 const double mass,
                 double* d,
                 const double rho,
                 const int gridtype,
                 const double* w,
                 const int w_d0,
                 const double* zero,
                 const int zero_d0,
                 const double* plx,
                 const int plx_d0,
                 const int plx_d1,
                 const int* n,
                 const double* dref,
                 int* exitstatus);
  void CilmPlusRhoH(double* cilm,
                    const int cilm_d,
                    const double* gridin,
                    const int gridin_d0,
                    const int gridin_d1,
                    const int lmax,
                    const int nmax,
                    const double mass,
                    double* d,
                    const double* rho,
                    const int rho_d0,
                    const int rho_d1,
                    const int gridtype,
                    const double* w,
                    const int w_d0,
                    const double* zero,
                    const int zero_d0,
                    const double* plx,
                    const int plx_d0,
                    const int plx_d1,
                    const int* n,
                    const double* dref,
                    int* exitstatus);
  void CilmMinusRhoH(double* cilm,
                     const int cilm_d,
                     const double* gridin,
                     const int gridin_d0,
                     const int gridin_d1,
                     const int lmax,
                     const int nmax,
                     const double mass,
                     double* d,
                     const double* rho,
                     const int rho_d0,
                     const int rho_d1,
                     const int gridtype,
                     const double* w,
                     const int w_d0,
                     const double* zero,
                     const int zero_d0,
                     const double* plx,
                     const int plx_d0,
                     const int plx_d1,
                     const int* n,
                     const double* dref,
                     int* exitstatus);
  void BAtoHilm(double* cilm,
                const int cilm_d,
                const double* ba,
                const int ba_d0,
                const int ba_d1,
                const int ba_d2,
                const double* gridglq,
                const int gridglq_d0,
                const int gridglq_d1,
                const int lmax,
                const int nmax,
                const double mass,
                const double r0,
                const double rho,
                const int gridtype,
                const double* w,
                const int w_d0,
                const double* plx,
                const int plx_d0,
                const int plx_d1,
                const double* zero,
                const int zero_d0,
                const int* filter_type,
                const int* filter_deg,
                const int* lmax_calc,
                int* exitstatus);
  void BAtoHilmRhoH(double* cilm,
                    const int cilm_d,
                    const double* ba,
                    const int ba_d0,
                    const int ba_d1,
                    const int ba_d2,
                    const double* gridglq,
                    const int gridglq_d0,
                    const int gridglq_d1,
                    const int lmax,
                    const int nmax,
                    const double mass,
                    const double r0,
                    const double* rho,
                    const int rho_d0,
                    const int rho_d1,
                    const int gridtype,
                    const double* w,
                    const int w_d0,
                    const double* plx,
                    const int plx_d0,
                    const int plx_d1,
                    const double* zero,
                    const int zero_d0,
                    const int* filter_type,
                    const int* filter_deg,
                    const int* lmax_calc,
                    int* exitstatus);
  double DownContFilterMA(const int l,
                          const int half,
                          const double r,
                          const double d);
  double DownContFilterMC(const int l,
                          const int half,
                          const double r,
                          const double d);
  double NormalGravity(const double geocentric_lat,
                       const double gm,
                       const double omega,
                       const double a,
                       const double b);
  void MakeMagGridDH(const double* cilm,
                     const int cilm_d,
                     const int lmax,
                     const double r0,
                     const double a,
                     const double f,
                     double* rad_grid,
                     const int rad_grid_d0,
                     const int rad_grid_d1,
                     double* theta_grid,
                     const int theta_grid_d0,
                     const int theta_grid_d1,
                     double* phi_grid,
                     const int phi_grid_d0,
                     const int phi_grid_d1,
                     double* total_grid,
                     const int total_grid_d0,
                     const int total_grid_d1,
                     int* n,
                     const int* sampling,
                     const int* lmax_calc,
                     double* pot_grid,
                     const int pot_grid_d0,
                     const int pot_grid_d1,
                     const int* extend,
                     int* exitstatus);
  void SHMagPowerSpectrum(const double* c,
                          const int c_d0,
                          const int c_d1,
                          const int c_d2,
                          const double a,
                          const double r,
                          const int lmax,
                          double* spectra,
                          const int spectra_d0,
                          int* exitstatus);
  double SHMagPowerL(const double* c,
                     const int c_d0,
                     const int c_d1,
                     const int c_d2,
                     const double a,
                     const double r,
                     const int l);
  void MakeCircleCoord(double* coord,
                       const int coord_d0,
                       const int coord_d1,
                       const double lat,
                       const double lon,
                       const double theta0,
                       const double* cinterval,
                       int* cnum,
                       int* exitstatus);
  void MakeEllipseCoord(double* coord,
                        const int coord_d0,
                        const int coord_d1,
                        const double lat,
                        const double lon,
                        const double dec,
                        const double A_theta,
                        const double B_theta,
                        const double* cinterval,
                        int* cnum,
                        int* exitstatus);
  void Wigner3j(double* w3j,
                const int w3j_d0,
                int* jmin,
                int* jmax,
                const int j2,
                const int j3,
                const int m1,
                const int m2,
                const int m3,
                int* exitstatus);
  double RandomN(int* idum);
  double RandomGaussian(int* idum);
  void PreGLQ(const double x1,
              const double x2,
              const int n,
              double* zero,
              const int zero_d0,
              double* w,
              const int w_d0,
              int* exitstatus);
  int NGLQ(const int degree);
  int NGLQSH(const int degree);
  int NGLQSHN(const int degree, const int n);
  void DHaj(const int n,
            double* aj,
            const int aj_d0,
            const int* extend,
            int* exitstatus);
  int YilmIndexVector(const int i, const int l, const int m);
  void EigValVecSym(const double* ain,
                    const int ain_d0,
                    const int ain_d1,
                    const int n,
                    double* eig,
                    const int eig_d0,
                    double* evec,
                    const int evec_d0,
                    const int evec_d1,
                    const char* ul,
                    const int* K,
                    int* exitstatus);
  void EigValVecSymTri(const double* ain,
                       const int ain_d0,
                       const int ain_d1,
                       const int n,
                       double* eig,
                       const int eig_d0,
                       double* evec,
                       const int evec_d0,
                       const int evec_d1,
                       const char* ul,
                       int* exitstatus);
  void EigValSym(const double* ain,
                 const int ain_d0,
                 const int ain_d1,
                 const int n,
                 double* eval,
                 const int eval_d0,
                 const char* ul);
  void SHRotateTapers(double* tapersrot,
                      const int tapersrot_d0,
                      const int tapersrot_d1,
                      const double* tapers,
                      const int tapers_d0,
                      const int tapers_d1,
                      const int* taper_order,
                      const int taper_order_d0,
                      const int lmax,
                      const int nrot,
                      const double* x,
                      const int x_d0,
                      const double* dj,
                      const int dj_d0,
                      const int dj_d1,
                      const int dj_d2,
                      int* exitstatus);
  void SlepianCoeffs(double* falpha,
                     const int falpha_d0,
                     const double* galpha,
                     const int galpha_d0,
                     const int galpha_d1,
                     const double* flm,
                     const int flm_d0,
                     const int flm_d1,
                     const int flm_d2,
                     const int lmax,
                     const int nmax,
                     int* exitstatus);
  void SlepianCoeffsToSH(double* flm,
                         const int flm_d0,
                         const int flm_d1,
                         const int flm_d2,
                         const double* falpha,
                         const int falpha_d0,
                         const double* galpha,
                         const int galpha_d0,
                         const int galpha_d1,
                         const int lmax,
                         const int nmax,
                         int* exitstatus);
  void SHSCouplingMatrix(double* kij,
                         const int kij_d0,
                         const int kij_d1,
                         const double* galpha,
                         const int galpha_d0,
                         const int galpha_d1,
                         const int lmax,
                         const int nmax,
                         int* exitstatus);
  void SHSlepianVar(const int l,
                    const double* galpha,
                    const int galpha_d0,
                    const int galpha_d1,
                    const int* galpha_order,
                    const int galpha_order_d0,
                    const int lmax,
                    const int kmax,
                    const double* Sff,
                    const int Sff_d0,
                    double* variance,
                    int* exitstatus);
  void SHSCouplingMatrixCap(double* kij,
                            const int kij_d0,
                            const int kij_d1,
                            const double* galpha,
                            const int galpha_d0,
                            const int galpha_d1,
                            const int* galpha_order,
                            const int galpha_order_d0,
                            const int lmax,
                            const int nmax,
                            int* exitstatus);
}
}
